[env]
CC_riscv32im_risc0_zkvm_elf = "clang"
CFLAGS_riscv32im_risc0_zkvm_elf = "-nostdlibinc -DRING_CORE_NOSTDLIBINC=1 -target riscv32-unknown-elf -march=rv32im"
RISC0_FEATURE_bigint2 = "1"

[target."riscv32im-risc0-zkvm-elf"]
linker = "/Users/.../risc0-tlsn-verifier/riscv32im-linker.sh"
rustflags = [
  "--cfg", "getrandom_backend=\"custom\"",
  "-C", "link-arg=-march=rv32im",
  "-C", "link-arg=-mabi=ilp32",
  "-C", "link-arg=-nostartfiles",
]

